kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t harness-demo:latest .

  - name: deploy
    image: bitnami/kubectl
    commands:
      - kubectl apply -f k8s.yaml

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock