apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harness-demo
  template:
    metadata:
      labels:
        app: harness-demo
    spec:
      containers:
        - name: harness-demo
          image: harness-demo:latest
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: harness-demo-service
spec:
  type: NodePort
  selector:
    app: harness-demo
  ports:
    - port: 3000
      targetPort: 3000